spring.application.name=backend-api

# Conexion a BD Local (Actualizar credenciales antes de correr)
# spring.datasource.url=jdbc:mysql://localhost:3306/hardpc_db?serverTimezone=America/Lima
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate
# ddl-auto=update para que no borre la data en cada reinicio
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update